//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Problem_04.StringsClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStringSearcherService")]
    public interface IStringSearcherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringSearcherService/GetCount", ReplyAction="http://tempuri.org/IStringSearcherService/GetCountResponse")]
        int GetCount(string a, string b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringSearcherService/GetCount", ReplyAction="http://tempuri.org/IStringSearcherService/GetCountResponse")]
        System.Threading.Tasks.Task<int> GetCountAsync(string a, string b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringSearcherServiceChannel : Problem_04.StringsClient.ServiceReference1.IStringSearcherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringSearcherServiceClient : System.ServiceModel.ClientBase<Problem_04.StringsClient.ServiceReference1.IStringSearcherService>, Problem_04.StringsClient.ServiceReference1.IStringSearcherService {
        
        public StringSearcherServiceClient() {
        }
        
        public StringSearcherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringSearcherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringSearcherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringSearcherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetCount(string a, string b) {
            return base.Channel.GetCount(a, b);
        }
        
        public System.Threading.Tasks.Task<int> GetCountAsync(string a, string b) {
            return base.Channel.GetCountAsync(a, b);
        }
    }
}
